### ISSUE TITLE
Option to applyPatches mutatively (without cloning object)

### ISSUE THREAD

**Issue by Ctrlmonster** [giusepperaso/structura.js#110]
Hey, thanks for making this awesome library!

I've been looking for a more performance minded alternative to immer, as I'm developing a latency sensitive browser game and want to send game-state patches over the wire, so structura seems like a perfect fit :)

Now my question/problem is whether it's possible to apply patches in a way that manipulates an existing object and skips the cloning step. Reason for needing this is that my object on the client side isn't just an object but only provides an object-like interface with custom setters that wire the data to some other place and I want to avoid re-creating this complex interface every time I receive patches.

```js
// something like
const res = applyPatchesMutatively(myObject, patches);
expect(res === myObject);
```
Cheers 🙌

**Comment by Ctrlmonster** [comment]
That was fast! @giusepperaso 

Works like a charm for me, thank you so much! 
I'll report back if I encounter any problems.

One small note, in the [docs](https://giusepperaso.github.io/structura.js/patches.html#apply-patches-mutatively) it says `Sometimes you may want to apply patches to an object without mutating it.`, the last part should probably be `without cloning it` :)

**Comment by giusepperaso** [comment]
oops thanks for noticing, I've corrected it
