### ISSUE TITLE
Equivalent of immers Immutable type

### ISSUE THREAD

**Issue by jantimon** [giusepperaso/structura.js#91]
hi :)

I wanted to try if my app would run faster with structura.js than it does right now with immer.

My immer code looks like this:

```ts
export const convertPatchesToDiff = <TState extends {}>(
  initialState: Immutable<TState>,
  transactions: Patch[][],
  derivateFn: (state: TState) => void
) => {
  const [initialDerivedState, , initialRevertDerivation] = produceWithPatches(
    initialState,
    derivateFn
  );
  // ...
```

I tried to find the equivalent for `Immutable` from immer.js.

I felt a little bit los as the `index.d.ts` files doesn't have many comments and most variables are named `T` or `Q`.  
But I guess that's fine given the early state of strucura.js.

I tried `Freeze`:

```ts
export const convertPatchesToDiff = <TState extends {}>(
  initialState: Freeze<TState>,
  transactions: Patch[][],
  derivateFn: (state: TState) => void
) => {
const [initialDerivedState, , initialRevertDerivation] = produceWithPatches(
    initialState,
    derivateFn
  );
  // ...
```

However this gives me the following type error:

```
Argument of type '(state: TState) => void' is not assignable to parameter of type 'Producer<Freeze<TState>, void>'.
  Types of parameters 'state' and 'draft' are incompatible.
    Type 'UnFreeze<Freeze<TState>>' is not assignable to type 'TState'.
```

Can you please let me know if there is already an equivalent of immers Immutable type?

**Comment by giusepperaso** [comment]
Hi @jantimon!

You are correct in using the Freeze type in that way, but the typing is slightly different for the derivateFn; 

besides a casting is also necessary in this particular case, which I will fix in a future version

```typescript
import { produceWithPatches, Freeze, Patch, Producer } from "structurajs";

export const convertPatchesToDiff = <TState extends {}>(
  initialState: Freeze<TState>,
  transactions: Patch[][],
  derivateFn: Producer<TState, void>
) => {
const [initialDerivedState, , initialRevertDerivation] = produceWithPatches(
    initialState as TState, // <-- this casting shouldn't be necessary in future versions
    derivateFn
  );
  //...
```

However the function name hints at the fact that you are trying to convert patches to a diff, but the patches generated by structura are not compliant with Immer (and with RFC 6902). For this reason your current logic will likely not work and should be rewritten to be compatible with structura patches, so this could require a bit of work

I already planned to add a way to convert patches generated by structura to the same format used by Immer for compatibility, but for now this is not implemented

**Comment by giusepperaso** [comment]
Closing the issue because related problems are solved starting from v.0.8.0

In a case like the above, one could now use the type FreezeOnce to have correct type inference

Besides, Structura is now compatible with standard JSON Patches, just import produceWithStandardPatches  (then you can apply them with applyPatches as normal)

```typescript
export const convertPatchesToDiff = <TState extends {}>(
  initialState: FreezeOnce<TState>,
  transactions: Patch[][],
  derivateFn: Producer<TState, void>
) => {
const [initialDerivedState, , initialRevertDerivation] = produceWithStandardPatches( // generate standard json patches
    initialState , // casting is no longer necessary
    derivateFn
  );
  //...
```

**Comment by jantimon** [comment]
thanks ❤️
